name: check who's turn it is
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  add-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run checkTurn
