name: check who's turn it is
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  add-to-sheet:
    runs-on: ubuntu-latest
    env:
      CI: true
      AGRICOLA_NOTIFICATION_CHANNEL_WEB_HOOK: ${{ secrets.AGRICOLA_NOTIFICATION_CHANNEL_WEB_HOOK }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run checkTurn
     - run: |        
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated last played"
          git push
